// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "regexp"

type Name string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Name) UnmarshalJSON(value []byte) error {
	type Plain Name
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z0-9.-]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z0-9.-]+$`)
	}
	*j = Name(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Name) UnmarshalYAML(value *yaml.Node) error {
	type Plain Name
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z0-9.-]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z0-9.-]+$`)
	}
	*j = Name(plain)
	return nil
}
