// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

type Schema struct {
	// Prop corresponds to the JSON schema field "prop".
	Prop SchemaOverride `json:"prop,omitempty,omitzero" yaml:"prop,omitempty" mapstructure:"prop,omitempty"`
}

// An overridden description
type SchemaOverride []int
