// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type Id int64

// UnmarshalJSON implements json.Unmarshaler.
func (j *Id) UnmarshalJSON(value []byte) error {
	type Plain Id
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 1)
	}
	*j = Id(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Id) UnmarshalYAML(value *yaml.Node) error {
	type Plain Id
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if 1 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 1)
	}
	*j = Id(plain)
	return nil
}
