// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type Outer struct {
	// MediaId corresponds to the JSON schema field "media_id".
	MediaId *int64 `json:"media_id,omitempty,omitzero" yaml:"media_id,omitempty" mapstructure:"media_id,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Outer) UnmarshalJSON(value []byte) error {
	type Plain Outer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.MediaId != nil && 1 > *plain.MediaId {
		return fmt.Errorf("field %s: must be >= %v", "media_id", 1)
	}
	*j = Outer(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Outer) UnmarshalYAML(value *yaml.Node) error {
	type Plain Outer
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.MediaId != nil && 1 > *plain.MediaId {
		return fmt.Errorf("field %s: must be >= %v", "media_id", 1)
	}
	*j = Outer(plain)
	return nil
}
