// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "regexp"

type Name string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Name) UnmarshalJSON(value []byte) error {
	type Plain Name
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z0-9.-]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z0-9.-]+$`)
	}
	*j = Name(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Name) UnmarshalYAML(value *yaml.Node) error {
	type Plain Name
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z0-9.-]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z0-9.-]+$`)
	}
	*j = Name(plain)
	return nil
}

type PatternRef struct {
	// MyNullableString corresponds to the JSON schema field "myNullableString".
	MyNullableString *Name `json:"myNullableString,omitempty,omitzero" yaml:"myNullableString,omitempty" mapstructure:"myNullableString,omitempty"`

	// MyString corresponds to the JSON schema field "myString".
	MyString Name `json:"myString" yaml:"myString" mapstructure:"myString"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PatternRef) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["myString"]; raw != nil && !ok {
		return fmt.Errorf("field myString in PatternRef: required")
	}
	type Plain PatternRef
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PatternRef(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *PatternRef) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["myString"]; raw != nil && !ok {
		return fmt.Errorf("field myString in PatternRef: required")
	}
	type Plain PatternRef
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = PatternRef(plain)
	return nil
}
