// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "regexp"

type BothNamed struct {
	// Field corresponds to the JSON schema field "field".
	Field *WrapperWithName `json:"field,omitempty,omitzero" yaml:"field,omitempty" mapstructure:"field,omitempty"`
}

type NamedTarget string

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamedTarget) UnmarshalJSON(value []byte) error {
	type Plain NamedTarget
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z]+$`)
	}
	*j = NamedTarget(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NamedTarget) UnmarshalYAML(value *yaml.Node) error {
	type Plain NamedTarget
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z]+$`)
	}
	*j = NamedTarget(plain)
	return nil
}

type WrapperWithName string

// UnmarshalJSON implements json.Unmarshaler.
func (j *WrapperWithName) UnmarshalJSON(value []byte) error {
	type Plain WrapperWithName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z]+$`)
	}
	*j = WrapperWithName(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *WrapperWithName) UnmarshalYAML(value *yaml.Node) error {
	type Plain WrapperWithName
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z]+$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z]+$`)
	}
	*j = WrapperWithName(plain)
	return nil
}
