// Code generated by github.com/tuotuoxp/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type NamedCount int

// UnmarshalJSON implements json.Unmarshaler.
func (j *NamedCount) UnmarshalJSON(value []byte) error {
	type Plain NamedCount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = NamedCount(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *NamedCount) UnmarshalYAML(value *yaml.Node) error {
	type Plain NamedCount
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = NamedCount(plain)
	return nil
}

type RefPrimitiveNamedTitleAdditionalProperties struct {
	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	AdditionalProperties map[string]NamedCount `mapstructure:",remain"`
}
